### ISSUE TITLE
Please link to this repo from rubygems.org

### ISSUE THREAD

**Issue by jaredbeck** [cph/mdb#6]
Congrats on the 0.4.0 release. I'm looking into upgrading. Had a mildly hard time finding this repo because there is no link from rubygems.org.

![links](https://cloud.githubusercontent.com/assets/380809/24156529/2fe3b64e-0e2d-11e7-8b5c-d41495d33eb5.jpg)

**Comment by boblail** [comment]
Good call. I added the repo's homepage in ab9dc42375389115c590bddb69ea4e6d50622e31
